### ISSUE TITLE
IP resolver

### ISSUE THREAD

**Issue by Ethaligan** [allthingsdns/allthingsdns#6]

**Comment by JulianKahnert** [comment]
Let's validate the IP address with this module:
https://docs.python.org/3/library/ipaddress.html

**Comment by JulianKahnert** [comment]
done in #11

**Comment by JulianKahnert** [comment]
I got a problem with the Resolver 😢 

```python
In [1]: from allthingsdns.helpers import Resolver

In [2]: resolve = Resolver('http')
ERROR:AllThingsDNS.allthingsdns.helpers:HTTPSConnectionPool(host='ipv6.icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110804320>: Failed to establish a new connection: [Errno 65] No route to host',))
Traceback (most recent call last):
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x110804320>: Failed to establish a new connection: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipv6.icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110804320>: Failed to establish a new connection: [Errno 65] No route to host',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliankahnert/Documents/GIT/allthingsdns/allthingsdns/helpers.py", line 110, in get_ip
    r = requests.get('https://ipv{}.icanhazip.com'.format(version))
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/juliankahnert/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipv6.icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110804320>: Failed to establish a new connection: [Errno 65] No route to host',))
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connection.py in _new_conn(self)
    140             conn = connection.create_connection(
--> 141                 (self.host, self.port), self.timeout, **extra_kw)
    142 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     82     if err is not None:
---> 83         raise err
     84 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     72                 sock.bind(source_address)
---> 73             sock.connect(sa)
     74             return sock

OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    600                                                   body=body, headers=headers,
--> 601                                                   chunked=chunked)
    602 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    345         try:
--> 346             self._validate_conn(conn)
    347         except (SocketTimeout, BaseSSLError) as e:

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
    849         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
--> 850             conn.connect()
    851 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connection.py in connect(self)
    283         # Add certificate verification
--> 284         conn = self._new_conn()
    285 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connection.py in _new_conn(self)
    149             raise NewConnectionError(
--> 150                 self, "Failed to establish a new connection: %s" % e)
    151 

NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x110804320>: Failed to establish a new connection: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    439                     retries=self.max_retries,
--> 440                     timeout=timeout
    441                 )

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    638             retries = retries.increment(method, url, error=e, _pool=self,
--> 639                                         _stacktrace=sys.exc_info()[2])
    640             retries.sleep()

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    387         if new_retry.is_exhausted():
--> 388             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    389 

MaxRetryError: HTTPSConnectionPool(host='ipv6.icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110804320>: Failed to establish a new connection: [Errno 65] No route to host',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
~/Documents/GIT/allthingsdns/allthingsdns/helpers.py in get_ip(self, version, method)
    109             try:
--> 110                 r = requests.get('https://ipv{}.icanhazip.com'.format(version))
    111             except requests.exceptions.RequestException as error:

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/api.py in get(url, params, **kwargs)
     71     kwargs.setdefault('allow_redirects', True)
---> 72     return request('get', url, params=params, **kwargs)
     73 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/api.py in request(method, url, **kwargs)
     57     with sessions.Session() as session:
---> 58         return session.request(method=method, url=url, **kwargs)
     59 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    507         send_kwargs.update(settings)
--> 508         resp = self.send(prep, **send_kwargs)
    509 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/sessions.py in send(self, request, **kwargs)
    617         # Send the request
--> 618         r = adapter.send(request, **kwargs)
    619 

~/.pyenv/versions/3.6.2/envs/allthingsdns/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    507 
--> 508             raise ConnectionError(e, request=request)
    509 

ConnectionError: HTTPSConnectionPool(host='ipv6.icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110804320>: Failed to establish a new connection: [Errno 65] No route to host',))

During handling of the above exception, another exception occurred:

ResolverException                         Traceback (most recent call last)
<ipython-input-2-9556e819779a> in <module>()
----> 1 resolve = Resolver('http')

~/Documents/GIT/allthingsdns/allthingsdns/helpers.py in __init__(self, method)
     94         self.ipv4 = self.get_ip(4, method)
     95         if socket.has_ipv6:
---> 96             self.ipv6 = self.get_ip(6, method)
     97         else:
     98             self.ipv6 = None

~/Documents/GIT/allthingsdns/allthingsdns/helpers.py in get_ip(self, version, method)
    111             except requests.exceptions.RequestException as error:
    112                 self.logger.exception(error)
--> 113                 raise ResolverException(error)
    114             return r.text.strip()
    115 

ResolverException: HTTPSConnectionPool(host='ipv6.icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110804320>: Failed to establish a new connection: [Errno 65] No route to host',))

```
